# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z030sbg485-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.cache/wt [current_project]
set_property parent.project_path /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:picozed_7030_fmc2:part0:1.1 [current_project]
set_property ip_repo_paths /home/adam/vivado_proj/ips [current_project]
set_property ip_output_repo /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.srcs/sources_1/new/event_timestamp.vhd
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top event_timestamp -part xc7z030sbg485-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef event_timestamp.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file event_timestamp_utilization_synth.rpt -pb event_timestamp_utilization_synth.pb"
