webtalk_init -webtalk_dir /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.sim/sim_1/behav/xsim/xsim.dir/tbevent_timestamp_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Nov 15 14:20:01 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174792386_175515640_210696347_360" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2831325dd69458a1ab6e633de45999bb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d9f78f8e6e4e486fa85229df5a32619f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "30" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4029.534 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131960_KB" -context "xsim\\usage"
webtalk_transmit -clientid 569249222 -regid "174792386_175515640_210696347_360" -xml /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.sim/sim_1/behav/xsim/xsim.dir/tbevent_timestamp_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.sim/sim_1/behav/xsim/xsim.dir/tbevent_timestamp_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/adam/Tresbox/vivado/openevr_event_timestamp/openevr_event_timestamp.sim/sim_1/behav/xsim/xsim.dir/tbevent_timestamp_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
